spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_test
    username: postgres
    password: quynhdev
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
  servlet:
    context-path: "/api/v1"
